version = 1

exclude_patterns = [
  "venv/",
  "static/raphael.js",
  "static/raphael.chord.js",
  "staticfiles/"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"