# Generated by Django 4.2.6 on 2023-12-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255)),
                ('tuning', models.CharField(blank=True, max_length=127)),
                ('key', models.CharField(blank=True, max_length=63)),
                ('capo', models.CharField(blank=True, max_length=127)),
                ('strumming', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('youtube', models.URLField(blank=True, max_length=511)),
                ('spotify', models.URLField(blank=True, max_length=511)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('to_publish', models.BooleanField(default=False)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('is_saved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privateentry_added_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'private entry',
                'verbose_name_plural': 'private entries',
            },
        ),
    ]
