# Generated by Django 4.2.6 on 2023-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(to='public.publicentry'),
        ),
    ]
